---

- assert:
    that:
    - region is defined
    - service is defined
    - env is defined
    - component is defined
    msg: "Required variable not set."

- name: Create the Auto Scaling Group
  ec2_asg:
    name: "{{ component | upper }}-{{ env | upper }}-{{ service | upper }}-ASG"
    region: "{{ region }}"
    load_balancers: "{{ load_balancers | default([]) }}"
    availability_zones: "{{ azs | default([]) }}"
    launch_config_name: "{{ launch_config }}"
    vpc_zone_identifier: "{{ subnet_ids }}"
    min_size: "{{ min_size | default(0) }}"
    max_size: "{{ max_size | default(1) }}"
#    desired_capacity: "{{ desired | default(0) }}"
  register: new_asg
