---

- assert:
    that:
    - region is defined
    - ami_id is defined
    - key_name is defined
    - sec_groups is defined
    - component is defined
    - iam_role is defined
    msg: "Required variable not set."

- name: Create launch config
  ec2_lc:
    name: "{{ component }}-lc"
    state: "{{ state | default('present') }}"
    region: "{{ region }}"
    image_id: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type  }}"
    security_groups: "{{ sec_groups }}"
    user_data_path: "{{ user_data }}"
    instance_profile_name: "{{ iam_role }}"
    assign_public_ip: "{{ public_ip | default('no') }}"
    ebs_optimized: "{{ ebs_optimise | default('no') }}"
  when: user_data is defined
