---

- assert:
    that:
    - region is defined
    - ami_id is defined
    - key_name is defined
    - sec_groups is defined
    - component is defined
    msg: "Required variable not set."

- name: Create launch config
  ec2_lc:
    # The name of the launch config is how Ansible decides whether to create the LC or not,
    # so we need the name to change if either the AMI or the userdata script changes.
    #
    name: "{{ launch_config }}"
    state: "{{ state | default('present') }}"
    region: "{{ region }}"
    image_id: "{{ ami_id }}"
    key_name: "{{ key_name }}"
    instance_type: "{{ instance_type  }}"
    security_groups: "{{ sec_groups }}"
    user_data: "{{ lookup('template', user_data) }}"
    instance_profile_name: "{{ iam_role | default('Default-ec2-Role') }}"
    assign_public_ip: "{{ public_ip | default('no') }}"
    ebs_optimized: "{{ ebs_optimise | default('no') }}"
  when: user_data is defined
